"""
kafka_config.py — Kafka topic definitions and partition strategies
C5 Spec: Exactly-once semantics, payment event processing
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional


class KafkaTopic(str, Enum):
    """Canonical Kafka topic names for the LIP platform.

    All topic names are prefixed ``lip.`` to namespace them within a shared
    cluster.  Partition keys default to ``uetr`` for event ordering per
    payment.

    Attributes:
        PAYMENT_EVENTS: Inbound ISO 20022 pacs.002 / FedNow / RTP / SEPA
            events from bank connectors.  24 partitions for throughput.
        FAILURE_PREDICTIONS: C1 classifier output with ``failure_probability``
            and SHAP features.  12 partitions.
        SETTLEMENT_SIGNALS: SWIFT / camt.054 settlement confirmations
            consumed by C3 Repayment Engine.  24 partitions.
        DISPUTE_RESULTS: C4 Dispute Classifier output.  6 partitions.
        VELOCITY_ALERTS: C6 AML velocity limit breaches.  6 partitions.
        LOAN_OFFERS: Outbound bridge-loan offers generated by C7.  6 partitions.
        REPAYMENT_EVENTS: C3 repayment confirmations.  6 partitions.
        DECISION_LOG: Immutable audit records for every LIP decision.
            **7-year retention** (``retention_ms = 7 * 365 * 24 * 3600 * 1000``)
            mandated by SR 11-7 model governance and EU AI Act Art.17.
            12 partitions.
        DEAD_LETTER: Unprocessable events from any topic.  6 partitions.
    """

    PAYMENT_EVENTS = "lip.payment.events"
    FAILURE_PREDICTIONS = "lip.failure.predictions"
    SETTLEMENT_SIGNALS = "lip.settlement.signals"
    DISPUTE_RESULTS = "lip.dispute.results"
    VELOCITY_ALERTS = "lip.velocity.alerts"
    LOAN_OFFERS = "lip.loan.offers"
    REPAYMENT_EVENTS = "lip.repayment.events"
    DECISION_LOG = "lip.decision.log"
    DEAD_LETTER = "lip.dead.letter"
    STRESS_REGIME = "lip.stress.regime"


@dataclass
class TopicConfig:
    """Configuration for a single Kafka topic.

    Attributes:
        topic: :class:`KafkaTopic` enum member this config applies to.
        partitions: Number of partitions.  Higher values increase throughput
            at the cost of consumer rebalance latency.
        replication_factor: Number of broker replicas (default 3 for
            production-grade durability).
        retention_ms: Log retention in milliseconds.  Default is 7 days
            (``7 * 24 * 3600 * 1000``).  **Exception**: ``DECISION_LOG``
            uses 7 years (``7 * 365 * 24 * 3600 * 1000``) for compliance.
        exactly_once: When ``True``, producers must use idempotent writes
            and transactional commits (``enable.idempotence=True``).
        partition_key: Message field used as the partition key.  Defaults
            to ``'uetr'`` to guarantee ordering of all events for a single
            payment on the same partition.
    """

    topic: KafkaTopic
    partitions: int
    replication_factor: int = 3
    retention_ms: int = 7 * 24 * 3600 * 1000  # 7 days default
    exactly_once: bool = True
    partition_key: str = "uetr"  # partition by UETR for ordering


TOPIC_DEFINITIONS: Dict[KafkaTopic, TopicConfig] = {
    KafkaTopic.PAYMENT_EVENTS: TopicConfig(
        topic=KafkaTopic.PAYMENT_EVENTS,
        partitions=24,
        exactly_once=True,
    ),
    KafkaTopic.FAILURE_PREDICTIONS: TopicConfig(
        topic=KafkaTopic.FAILURE_PREDICTIONS,
        partitions=12,
    ),
    KafkaTopic.SETTLEMENT_SIGNALS: TopicConfig(
        topic=KafkaTopic.SETTLEMENT_SIGNALS,
        partitions=24,
    ),
    KafkaTopic.DISPUTE_RESULTS: TopicConfig(
        topic=KafkaTopic.DISPUTE_RESULTS,
        partitions=6,
    ),
    KafkaTopic.VELOCITY_ALERTS: TopicConfig(
        topic=KafkaTopic.VELOCITY_ALERTS,
        partitions=6,
    ),
    KafkaTopic.LOAN_OFFERS: TopicConfig(
        topic=KafkaTopic.LOAN_OFFERS,
        partitions=6,
    ),
    KafkaTopic.REPAYMENT_EVENTS: TopicConfig(
        topic=KafkaTopic.REPAYMENT_EVENTS,
        partitions=6,
    ),
    KafkaTopic.DECISION_LOG: TopicConfig(
        topic=KafkaTopic.DECISION_LOG,
        partitions=12,
        retention_ms=7 * 365 * 24 * 3600 * 1000,  # 7 years for compliance
    ),
    KafkaTopic.DEAD_LETTER: TopicConfig(
        topic=KafkaTopic.DEAD_LETTER,
        partitions=6,
    ),
    KafkaTopic.STRESS_REGIME: TopicConfig(
        topic=KafkaTopic.STRESS_REGIME,
        partitions=6,
        retention_ms=7 * 24 * 3600 * 1000,  # 7 days — risk alert signals
        exactly_once=False,  # fire-and-forget; at-least-once acceptable for alerts
    ),
}


@dataclass
class KafkaConfig:
    """Producer/consumer Kafka connection configuration for LIP.

    All fields default to production-safe values that enforce
    exactly-once semantics (EOS) via idempotent producers and
    ``isolation.level=read_committed`` consumers.

    Attributes:
        bootstrap_servers: List of ``host:port`` broker addresses.
        security_protocol: Kafka security protocol (default ``'SSL'``).
        ssl_ca_location: Path to the CA certificate for TLS verification.
        ssl_cert_location: Path to the client certificate for mTLS.
        ssl_key_location: Path to the client private key for mTLS.
        enable_idempotence: Enables producer idempotence (required for EOS).
        acks: Producer acknowledgement mode; ``'all'`` ensures ISR durability.
        max_in_flight_requests_per_connection: Must be ``1`` for exactly-once
            ordering guarantees.
        transactional_id: Optional transactional producer ID; set per-instance
            when using Kafka transactions (e.g., C7 decision logging).
    """

    bootstrap_servers: List[str] = field(default_factory=lambda: ["kafka:9092"])
    security_protocol: str = "SSL"
    ssl_ca_location: str = "/etc/ssl/kafka/ca.crt"
    ssl_cert_location: str = "/etc/ssl/kafka/client.crt"
    ssl_key_location: str = "/etc/ssl/kafka/client.key"
    enable_idempotence: bool = True  # exactly-once
    acks: str = "all"
    max_in_flight_requests_per_connection: int = 1  # exactly-once requires this
    transactional_id: Optional[str] = None

    def to_producer_config(self) -> dict:
        """Build a confluent-kafka / librdkafka producer configuration dict.

        Includes all TLS, idempotence, and ack settings.  When
        :attr:`transactional_id` is set, adds ``transactional.id`` for
        transactional producer use.

        Returns:
            Dict of librdkafka configuration key-value pairs suitable for
            passing directly to ``confluent_kafka.Producer(config)``.
        """
        cfg = {
            "bootstrap.servers": ",".join(self.bootstrap_servers),
            "security.protocol": self.security_protocol,
            "ssl.ca.location": self.ssl_ca_location,
            "ssl.certificate.location": self.ssl_cert_location,
            "ssl.key.location": self.ssl_key_location,
            "enable.idempotence": self.enable_idempotence,
            "acks": self.acks,
            "max.in.flight.requests.per.connection": self.max_in_flight_requests_per_connection,
        }
        if self.transactional_id:
            cfg["transactional.id"] = self.transactional_id
        return cfg

    def to_consumer_config(self, group_id: str) -> dict:
        """Build a confluent-kafka / librdkafka consumer configuration dict.

        Sets ``enable.auto.commit=False`` and
        ``isolation.level=read_committed`` to enforce exactly-once
        consumption semantics in conjunction with transactional producers.

        Args:
            group_id: Kafka consumer group identifier for this consumer
                instance.

        Returns:
            Dict of librdkafka configuration key-value pairs suitable for
            passing directly to ``confluent_kafka.Consumer(config)``.
        """
        return {
            "bootstrap.servers": ",".join(self.bootstrap_servers),
            "security.protocol": self.security_protocol,
            "ssl.ca.location": self.ssl_ca_location,
            "ssl.certificate.location": self.ssl_cert_location,
            "ssl.key.location": self.ssl_key_location,
            "group.id": group_id,
            "auto.offset.reset": "earliest",
            "enable.auto.commit": False,  # manual commit for exactly-once
            "isolation.level": "read_committed",
        }
