"""
P10 regulatory data product constants.

All privacy thresholds require QUANT + CIPHER sign-off to change.
"""
from lip.common.constants import (
    P10_AMOUNT_BUCKET_THRESHOLDS,
    P10_AMOUNT_BUCKETS,
    P10_DIFFERENTIAL_PRIVACY_EPSILON,
    P10_K_ANONYMITY_THRESHOLD,
    P10_PRIVACY_BUDGET_CYCLE_DAYS,
    P10_PRIVACY_BUDGET_PER_CYCLE,
    P10_TIMESTAMP_BUCKET_HOURS,
    SALT_ROTATION_DAYS,
    SALT_ROTATION_OVERLAP_DAYS,
)

__all__ = [
    "P10_AMOUNT_BUCKET_THRESHOLDS",
    "P10_AMOUNT_BUCKETS",
    "P10_DIFFERENTIAL_PRIVACY_EPSILON",
    "P10_K_ANONYMITY_THRESHOLD",
    "P10_PRIVACY_BUDGET_CYCLE_DAYS",
    "P10_PRIVACY_BUDGET_PER_CYCLE",
    "P10_TIMESTAMP_BUCKET_HOURS",
    "SALT_ROTATION_DAYS",
    "SALT_ROTATION_OVERLAP_DAYS",
]
