"""
P10 regulatory data product constants.

All privacy thresholds require QUANT + CIPHER sign-off to change.
"""
from lip.common.constants import (
    P10_AMOUNT_BUCKET_THRESHOLDS,
    P10_AMOUNT_BUCKETS,
    P10_CIRCULAR_EXPOSURE_MAX_LENGTH,
    P10_CIRCULAR_EXPOSURE_MIN_WEIGHT,
    P10_CONTAGION_MAX_HOPS,
    P10_CONTAGION_PROPAGATION_DECAY,
    P10_CONTAGION_STRESS_THRESHOLD,
    P10_DIFFERENTIAL_PRIVACY_EPSILON,
    P10_HHI_CONCENTRATION_THRESHOLD,
    P10_K_ANONYMITY_THRESHOLD,
    P10_MAX_HISTORY_PERIODS,
    P10_PRIVACY_BUDGET_CYCLE_DAYS,
    P10_PRIVACY_BUDGET_PER_CYCLE,
    P10_TELEMETRY_MIN_AMOUNT_USD,
    P10_TIMESTAMP_BUCKET_HOURS,
    P10_TREND_RISING_THRESHOLD,
    P10_TREND_WINDOW_PERIODS,
    SALT_ROTATION_DAYS,
    SALT_ROTATION_OVERLAP_DAYS,
)

__all__ = [
    "P10_AMOUNT_BUCKET_THRESHOLDS",
    "P10_AMOUNT_BUCKETS",
    "P10_CIRCULAR_EXPOSURE_MAX_LENGTH",
    "P10_CIRCULAR_EXPOSURE_MIN_WEIGHT",
    "P10_CONTAGION_MAX_HOPS",
    "P10_CONTAGION_PROPAGATION_DECAY",
    "P10_CONTAGION_STRESS_THRESHOLD",
    "P10_DIFFERENTIAL_PRIVACY_EPSILON",
    "P10_HHI_CONCENTRATION_THRESHOLD",
    "P10_K_ANONYMITY_THRESHOLD",
    "P10_MAX_HISTORY_PERIODS",
    "P10_PRIVACY_BUDGET_CYCLE_DAYS",
    "P10_PRIVACY_BUDGET_PER_CYCLE",
    "P10_TELEMETRY_MIN_AMOUNT_USD",
    "P10_TIMESTAMP_BUCKET_HOURS",
    "P10_TREND_RISING_THRESHOLD",
    "P10_TREND_WINDOW_PERIODS",
    "SALT_ROTATION_DAYS",
    "SALT_ROTATION_OVERLAP_DAYS",
]
